language: objective-c
osx_image: xcode8

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - XCODE_WORKSPACE=./Example/MBNetwork.xcworkspace
  matrix:
    - SCHEME="MBNetwork-Example"

before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet

script:
  - set -o pipefail
  - xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -configuration Debug clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  - xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -configuration Release clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

notifications:
  email: false
